import { Express } from "express";
import { dashboardRoutes } from "./dashboard-route";
import { topicRoutes } from "./topic-route";
import { songRoutes } from "./song-route";
import { singerRoutes } from "./singer-route";
import { systemConfig } from "../../config/config";
import { uploadRoutes } from "./upload-route";
import { accountRoutes } from "./account-route";
import { authRoutes } from "./auth-route";
import { authMiddleware } from "../../middlewares/admin/auth.middleware";
const adminRoutes = (app: Express): void => {
  const PATH_ADMIN = systemConfig.prefixAdmin;
  app.use(`${PATH_ADMIN}/dashboard`, authMiddleware, dashboardRoutes);
  app.use(`${PATH_ADMIN}/topics`, authMiddleware, topicRoutes);
  app.use(`${PATH_ADMIN}/songs`, authMiddleware, songRoutes);
  app.use(`${PATH_ADMIN}/singers`, authMiddleware, singerRoutes);
  app.use(`${PATH_ADMIN}/upload`, authMiddleware, uploadRoutes);
  app.use(`${PATH_ADMIN}/accounts`, authMiddleware, accountRoutes);
  app.use(`${PATH_ADMIN}/auth`, authRoutes);
};
export default adminRoutes;
